<script lang="ts">
  import type { SearchResult } from "@discord-music/contracts"
  import MagnifyingGlass from "phosphor-svelte/lib/MagnifyingGlass"
  import MusicNotes from "phosphor-svelte/lib/MusicNotes"
  import Plus from "phosphor-svelte/lib/Plus"
  import SkipForward from "phosphor-svelte/lib/SkipForward"
  import Button from "./Button.svelte"
  let { results, loading, error, onsearch, onadd }: { results: readonly SearchResult[]; loading: boolean; error: string | null; onsearch: (query: string) => void; onadd: (result: SearchResult, next: boolean) => void } = $props()
  let query = $state("")
  const providerLabel = (provider: SearchResult["track"]["provider"]): string =>
    provider === "mock_tidal" ? "Mock TIDAL · local lossless" : provider
</script>
<section class="search" aria-labelledby="search-title"><div><p class="eyebrow">Request a track</p><h2 id="search-title">Search</h2></div>{#if error}<p class="error" role="alert">{error}</p>{/if}<form onsubmit={(event) => { event.preventDefault(); onsearch(query) }}><label><span class="sr-only">Track name or link</span><MagnifyingGlass size={20} aria-hidden="true" /><input bind:value={query} placeholder="Track name or link" required /></label><Button label="Search" variant="primary" {loading} /></form>{#if !loading && results.length === 0}<div class="empty"><MusicNotes size={28} weight="duotone" aria-hidden="true" /><div><strong>Ready for requests</strong><span>Search by song, artist, or YouTube link.</span></div></div>{:else}<ul>{#each results as result (result.track.id)}<li data-testid="search-result" data-track-id={result.track.id}><div><strong>{result.track.title}</strong><span>{result.track.artist} · {providerLabel(result.track.provider)}</span></div><div><button aria-label={`Add ${result.track.title} to end`} onclick={() => onadd(result,false)}><Plus size={20} aria-hidden="true" /></button><button aria-label={`Play ${result.track.title} next`} onclick={() => onadd(result,true)}><SkipForward size={20} aria-hidden="true" /></button></div></li>{/each}</ul>{/if}</section>
<style>
  .search{inline-size:min(100%,var(--panel-max));margin-inline:auto;display:grid;gap:var(--space-3);padding:var(--space-5);background:var(--surface-recessed);border-radius:var(--radius-surface)}h2{margin:0}.eyebrow{text-transform:uppercase;font-size:var(--type-label);letter-spacing:var(--tracking-label);color:var(--text-muted)}form{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:var(--space-2)}label{min-block-size:var(--target);display:flex;align-items:center;gap:var(--space-2);padding-inline:var(--space-3);background:var(--surface-raised);border-radius:var(--radius-control)}input{min-inline-size:0;inline-size:100%;border:0;outline:0;background:transparent;color:var(--text-primary)}ul{display:grid;gap:var(--space-2);list-style:none;padding:0;margin:0}li{display:flex;justify-content:space-between;align-items:center;gap:var(--space-3);padding-block:var(--space-2);border-block-end:var(--line-width) solid var(--line-subtle)}li>div:first-child{min-inline-size:0;display:grid}li strong,li span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}li span{color:var(--text-secondary)}li>div:last-child{display:flex}li button{inline-size:var(--target);block-size:var(--target);display:grid;place-items:center;border:0;background:transparent;color:var(--text-secondary)}li button:hover{background:var(--surface-hover);color:var(--text-primary)}.empty{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:var(--space-3);min-block-size:calc(var(--space-12) + var(--space-4));padding:var(--space-4);background:var(--surface-primary);border-radius:var(--radius-control);color:var(--text-muted)}.empty div{min-inline-size:0;display:grid;gap:var(--space-1)}.empty strong{color:var(--text-secondary)}.empty span{overflow-wrap:anywhere}.error{color:var(--status-error)}.sr-only{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip:rect(0,0,0,0)}
  @media(max-width:480px){form{grid-template-columns:1fr}li{align-items:start}}
</style>
